### ISSUE TITLE
Release 0.1.8?

### ISSUE THREAD

**Issue by brianpgerson** [pbernasconi/react-plaid-link#13]
I saw you updated the src but NPM still has you at a release pegged to January, I believe. Would love to use v2 (`apiVersion`) but would rather keep an external dependency. Let me know if you can release this out (if it's ready!) or if I should just clone my own.

Thanks!

**Comment by pbernasconi** [comment]
Thanks for raising this issue! Just bumped the version to 0.1.9!

**Comment by brianpgerson** [comment]
Dope, thank you!
