### ISSUE TITLE
Depreciation of React.createClass

### ISSUE THREAD

**Issue by cedric-damien** [pbernasconi/react-plaid-link#17]
#Hi,
* Thank you very much for your time, and your amazing work, I am using plaidlink for one week and it works perfectly, thank you again. The only issue is that React. createClass is deprecated, do you plan to start using class PlaidLinks extends Component?
* Best Regards and thank you again for your time.

**Comment by chennighan** [comment]
@cedric-damien I noticed the same thing.

**Comment by pbernasconi** [comment]
Agreed – will look into getting this done in the coming weeks thanks for raising the issue @cedric-damien @chennighan

**Comment by gilakos** [comment]
Hi @pbernasconi, we just refactored `PlaidLink.js` to follow ES6 formatting with `extends Component`. Shall I fork and submit a PR?

**Comment by pbernasconi** [comment]
@gilakos that would be great actually - I'd gladly accept any improvements to this library

**Comment by gilakos** [comment]
@pbernasconi Just submitted a PR:
https://github.com/pbernasconi/react-plaid-link/pull/21
