### ISSUE TITLE
Is same day micro deposits auth possible with this component? 

### ISSUE THREAD

**Issue by firaskrichi** [pbernasconi/react-plaid-link#41]
Is same day micro deposits auth possible with this component? It doesn't seem to be working for me.

**Comment by pbernasconi** [comment]
@firaskrichi – Just released a new version [v1.2.0](https://github.com/pbernasconi/react-plaid-link/releases/tag/v1.2.0) with new Auth support!

Example code:
```jsx
<PlaidLink
  clientName="Plaid Client"
  env="sandbox"
  product={['auth', 'transactions']}
  publicKey="614be98f819e9bd8d0db9abec1c08a"
  className="some-class-name"
  user={{
    legalName: 'John Appleseed',
    emailAddress: 'john@companylogin.com',
  }}
  onSuccess={this.handleOnSuccess}
  onExit={this.handleOnExit}
  onEvent={this.handleOnEvent}
  onLoad={this.handleOnLoad}>
    Connect your bank account
</PlaidLink>
```

Thanks for flagging, and LMK how your integration goes.

**Comment by firaskrichi** [comment]
Thanks @pbernasconi for the quick turnaround here :)

**Comment by IconUploads** [comment]
Not able to test the feature even if added the user object
user={{
    legalName: 'John Appleseed',
    emailAddress: 'john@companylogin.com',
  }}

**Comment by sanuksoman** [comment]
not able to test feature even if added the user obejct.
user={{
    legalName: 'John Appleseed',
    emailAddress: 'john@companylogin.com',
  }}
