### ISSUE TITLE
Metadata is null

### ISSUE THREAD

**Issue by v5out** [pbernasconi/react-plaid-link#54]
At the top of handleOnSuccess, the console log shows metadata is null and therefore metadata.account_id is null, token is the correct value.

import React, { Component } from 'react'
import PlaidLink from 'react-plaid-link'
import axios from 'axios';

class Plaid extends Component {
  constructor(props) {
    super(props);
  }
  handleOnSuccess(token, metadata) {
    console.log(token)
    console.log(metadata.account_id)

    axios.post(...
      }).then(function (response) {
        console.log(response)
      }).catch(function (error) {
        console.log(error.message)
      });
  }
  handleOnExit() {
    console.log('link: user exited');
    console.log(error, metadata);
  }
  handleOnLoad() {
    console.log('link: loaded');
  }
  handleOnEvent(eventname, metadata) {
    console.log('link: user event', eventname, metadata);
  }
  render() {
    return (
      <PlaidLink
        clientName="CoName"
        env="sandbox"
        product={["transactions"]}
        publicKey="MY_KEY"
        onExit={this.handleOnExit}
        onSuccess={this.handleOnSuccess}>
        Open Link and connect your bank!
      </PlaidLink>
    )
  }
}
export default Plaid

**Comment by v5out** [comment]
User error

**Comment by dradeng** [comment]
What was the error, do you remember? I'm having a similiar problem where some of my metadata is null, ie metadata.account_id
